# GitHub actions
# https://docs.github.com/en/free-pro-team@latest/actions

name: ci-test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.44.4]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v4
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: format check
        run: deno fmt --check mod.ts utils/* scripts/* tests/*
      - name: run linter
        run: deno lint mod.ts utils/* scripts/* tests/*
      - name: run test
        run: deno test --allow-all --coverage=cov/

      - name: Generate coverage report
        run: deno coverage --lcov cov > cov.lcov

      - name: Upload coverage to Coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: cov.lcov
